### ISSUE TITLE
Добавить .gitignore в репозиторий

### ISSUE THREAD

**Issue by incrize** [AlexPosnov/notifier#1]
Подробная информация про gitignore тут https://git-scm.com/docs/gitignore

**Comment by AlexPosnov** [comment]
сделано

**Comment by incrize** [comment]
@AlexPosnov указывай, пожалуйста, коммит в котором это было сделано. 
P.S. если комментарий коммита будет правильно сформирован, то github сам слинкует коммит и issue, подробнее тут: https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests
